apiVersion: v1
kind: Secret
metadata:
  name: {{ template "daily-monetization.fullname" . }}-files
  labels:
    app: {{ template "daily-monetization.name" . }}
    chart: {{ template "daily-monetization.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  serviceAccount.json: |-
    {{ .Values.appConfig.serviceAccount }}

