apiVersion: v1
kind: Secret
metadata:
  name: {{ template "daily-monetization.fullname" . }}
  labels:
    app: {{ template "daily-monetization.name" . }}
    chart: {{ template "daily-monetization.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  DB_CONNECTION_STRING: {{ .Values.appConfig.dbConnectionString | quote }}
  MIGRATIONS_SOURCE: {{ .Values.appConfig.migrationsSource | quote }}
  CODEFUND_API_KEY: {{ .Values.appConfig.codefundApiKey | quote }}

